baseURL = 'https://craig-xu.github.io'
languageCode = 'en-us'
title = 'Craig Xu'
theme = 'diary'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "gruvbox"
    tabWidth = 4

[params]
  enableLaTeX=true  

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2